[databricks]
# Existing cluster id for computation
existing_cluster_id = '0616-121029-3n0ot9ei'
# Full notebook path
notebook_path = '/Repos/mahendra.z@sigmoidanalytics.com/prefect-databrick/src/databricks_notebooks/' 
# dbfs storage folder path
dbfs_folder_path = '/FileStore/assignment/mahendra/'
# data storage csv file name
data_file_name = 'latest-covid-data.csv'
# result storage csv file name
result_file_name = 'covid-analysis-result.csv'

[api]
host = 'covid19-data.p.rapidapi.com'
url = "https://${api.host}"
countries = 'Antigua and Barbuda,Albania,Armenia,Angola,Argentina,Austria,Australia,Azerbaijan,Bosnia and Herzegovina,Barbados,Bangladesh,Belgium,Burkina Faso,Bulgaria,Bahrain,Burundi,Benin,Bolivia,Brazil,Bahamas'
